export const testStore = {
	user: "신지수",
	vanCode: "code",
	vanId: "",
	note: "",
	contractImg: [],
	contractDate: "2023-01-23",
	storeName: "가맹점생성테스트",
	businessNum: "9999999999",
	isBackup: false,
	owner: "김미래",
	product: {
		cat: false,
		kiosk: true,
		pos: true,
		printer: false,
		router: false,
	},
	van: "KICC",
	city: "시흥시",
	address: "시흥시 주소 주소",
	cms: 33000,
	isCorporation: false,
}
